language: r
r: 
    #- bioc-devel
    - bioc-release
warnings_are_errors: false # :ToDo: comment out
sudo: false
cache: packages

r_packages:
      - covr

os:
  - linux
    #  - osx

bioc_required: true
bioc_packages:
  - BiocCheck

# # :ToDo: uncomment
# after_script:
#   - ls -lah
#   - FILE=$(ls -1t *.tar.gz | head -n 1)
#   - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
# 
# after_success:
#   - Rscript -e 'covr::codecov()'

# Something happend to osx bioc-devel builds 
matrix:
  exclude:
  - os: osx
    r: bioc-devel

# for loading cplex libraries
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - wget https://github.com/ctlab/private-libraries/archive/master.tar.gz -O - | tar -C ~ --strip-components 1 -xf -
  - ls ~
  - ls ~/lib
  - wget https://www.dropbox.com/s/hu9e8ihtyc0f0uh/gmwcs-signal.jar?raw=1 -O ~/lib/sgmwcs.jar
  - ls ~/lib

